package:
  name: signal_processing
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - signal-processing-core
    - pybind11 >=2.10.0

  run:
    - python


test:
  imports:
    - signal_processing
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  summary: c++ libery for siganl processing made for python 
  license_file: LICENSE
